services:
  librinote:
    build:
      context: .
      dockerfile: Dockerfile
    image: librinote:latest
    container_name: librinote
    restart: unless-stopped
    ports:
      - "13378:80"
    environment:
      - TZ=Europe/Vienna
    volumes:
      - /share/Multimedia/audiobookshelf/Config:/config
      - /share/Multimedia/audiobookshelf/metadata:/metadata
      - /share/Multimedia/audiobookshelf/Audiobook:/audiobooks
      - /share/Multimedia/audiobookshelf/Book:/Book
      - /share/Multimedia/audiobookshelf/Podcasts:/podcasts
